set_property PACKAGE_PIN K15 [get_ports mux_out[0]]        
set_property IOSTANDARD LVCMOS33 [get_ports mux_out[0]]
set_property PACKAGE_PIN J14 [get_ports mux_out[1]] 
set_property IOSTANDARD LVCMOS33 [get_ports mux_out[1]]
set_property PACKAGE_PIN H12 [get_ports mux_out[2]] 
set_property IOSTANDARD LVCMOS33 [get_ports mux_out[2]]
set_property PACKAGE_PIN G11 [get_ports mux_out[3]] 
set_property IOSTANDARD LVCMOS33 [get_ports mux_out[3]]
